include:
  - docker-compose-db.yml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: docent_backend
    ports:
      - "${DOCENT_SERVER_PORT:-8888}:${DOCENT_SERVER_PORT:-8888}"
    depends_on:
      - postgres
      - redis
    # Uncomment to forward SSH agent to the container
    # volumes:
    #   - ${SSH_AUTH_SOCK}:/ssh-agent
    # environment:
    #   - SSH_AUTH_SOCK=/ssh-agent
    environment:
      - ENV_RESOLUTION_STRATEGY=os_environ
      - DOCENT_PG_HOST=postgres
      - DOCENT_REDIS_HOST=redis
    command: bash -c "docent_core server --port ${DOCENT_SERVER_PORT:-8888} --workers 8"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: docent_worker
    depends_on:
      - postgres
      - redis
    environment:
      - ENV_RESOLUTION_STRATEGY=os_environ
      - DOCENT_PG_HOST=postgres
      - DOCENT_REDIS_HOST=redis
    command: bash -c "docent_core worker --workers 2"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_HOST=${DOCENT_HOST:-http://localhost}:${DOCENT_SERVER_PORT:-8888}
    container_name: docent_frontend
    ports:
      - "${DOCENT_WEB_PORT:-3000}:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_INTERNAL_API_HOST=http://backend:${DOCENT_SERVER_PORT:-8888}
    restart: unless-stopped
