# Fly.io configuration for Docent Backend API
# This runs PostgreSQL, Redis, Backend API, and Worker

app = "docent-api"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile.backend.fly"

[env]
  ENV_RESOLUTION_STRATEGY = "os_environ"
  DOCENT_SERVER_PORT = "8888"
  # Database
  DOCENT_PG_HOST = "localhost"
  DOCENT_PG_PORT = "5432"
  DOCENT_PG_USER = "docent_user"
  DOCENT_PG_DATABASE = "docent_db"
  # Redis
  DOCENT_REDIS_HOST = "localhost"
  DOCENT_REDIS_PORT = "6379"
  # LLM Cache
  LLM_CACHE_PATH = "/app/cache/llm"
  # CORS - allow frontend domain
  DOCENT_CORS_ORIGINS = "https://docent.fly.dev"

# HTTP service for the API
[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  # Health check for the API - uses root endpoint
  [[http_service.checks]]
    grace_period = "120s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/"

# VM configuration
[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2

# Persistent volume for PostgreSQL data
[mounts]
  source = "docent_api_pgdata"
  destination = "/var/lib/postgresql/data"
  initial_size = "10gb"

# Deployment configuration
[deploy]
  strategy = "rolling"
  release_command = "/app/scripts/pre-deploy.sh"

# Process groups
[processes]
  app = "/app/scripts/start-backend.sh"

# Secrets to set:
# flyctl secrets set DOCENT_PG_PASSWORD=<strong-password> --app docent-api
