# Fly.io configuration for Docent Frontend (password protected)

app = "docent"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile.frontend.fly"

[env]
  # Use same-origin for API requests (Next.js will proxy to backend)
  # This ensures cookies work properly for authentication
  NEXT_PUBLIC_API_HOST = "https://docent.fly.dev"
  NEXT_PUBLIC_INTERNAL_API_HOST = "https://docent-api.fly.dev"

# HTTP service for the frontend
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  # Health check
  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/health"

# VM configuration
[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# Deployment configuration
[deploy]
  strategy = "rolling"

# Process groups
[processes]
  app = "/app/scripts/start-frontend.sh"

# Secrets to set:
# flyctl secrets set AUTH_USERNAME=admin AUTH_PASSWORD=monitor-master --app docent
