# Fly.io configuration for Docent Backend
# This configuration runs backend, worker, PostgreSQL, and Redis

app = "docent-backend"
primary_region = "ams"  # Amsterdam, Netherlands - change as needed

[build]
  dockerfile = "Dockerfile.backend.fly"

[env]
  ENV_RESOLUTION_STRATEGY = "os_environ"
  # Backend
  DOCENT_SERVER_PORT = "8888"
  # Database
  DOCENT_PG_HOST = "localhost"
  DOCENT_PG_PORT = "5432"
  DOCENT_PG_USER = "docent_user"
  DOCENT_PG_DATABASE = "docent_db"
  # Redis
  DOCENT_REDIS_HOST = "localhost"
  DOCENT_REDIS_PORT = "6379"
  # CORS - allow requests from frontend
  DOCENT_CORS_ORIGINS = "https://docent-frontend.fly.dev"

# Main HTTP service (backend API)
[http_service]
  internal_port = 8888  # Backend port
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  # Health check for the backend
  [[http_service.checks]]
    grace_period = "120s"  # Increased for PostgreSQL initialization
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/"

# VM configuration - adjust based on your needs
[[vm]]
  memory = "2gb"  # Increased for running multiple services
  cpu_kind = "shared"
  cpus = 2

# Persistent volume for PostgreSQL data
[mounts]
  source = "docent_backend_pgdata"
  destination = "/var/lib/postgresql/data"
  initial_size = "10gb"

# Deployment configuration
[deploy]
  strategy = "rolling"
  # Run migrations before deployment
  release_command = "/app/scripts/pre-deploy.sh"

# Process groups - all processes run in the same VM
[processes]
  app = "/app/scripts/start-backend.sh"

# Secrets to set via `flyctl secrets set`:
# Required:
#   flyctl secrets set DOCENT_PG_PASSWORD=<strong-password> -a docent-backend
#
# Optional (for LLM providers):
#   flyctl secrets set OPENAI_API_KEY=<your-key> -a docent-backend
#   flyctl secrets set ANTHROPIC_API_KEY=<your-key> -a docent-backend
#   flyctl secrets set GOOGLE_API_KEY=<your-key> -a docent-backend
#
# Optional (for monitoring):
#   flyctl secrets set SENTRY_DSN=<your-dsn> -a docent-backend
#   flyctl secrets set POSTHOG_API_KEY=<your-key> -a docent-backend
#
# Optional (deployment tracking):
#   flyctl secrets set DEPLOYMENT_ID=production -a docent-backend

