# Fly.io configuration for Docent Frontend
# This configuration runs only the Next.js frontend

app = "docent-frontend"
primary_region = "ams"  # Amsterdam, Netherlands - change as needed

[build]
  dockerfile = "Dockerfile.frontend.fly"

[env]
  ENV_RESOLUTION_STRATEGY = "os_environ"
  # Frontend - point to backend API
  NEXT_PUBLIC_API_HOST = "https://docent-backend.fly.dev"
  NEXT_PUBLIC_INTERNAL_API_HOST = "https://docent-backend.fly.dev"

# Main HTTP service (frontend)
[http_service]
  internal_port = 3000  # Frontend port
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  # Health check for the frontend
  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/signup"

# VM configuration - smaller since it's just the frontend
[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# Deployment configuration
[deploy]
  strategy = "rolling"

# Process groups
[processes]
  app = "/app/scripts/start-frontend.sh"

# No secrets needed for frontend - all config is in env vars above

