# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  # Console exporter for real-time viewing
  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

  file:
    path: /data/otel-data.json
    format: json
    # rotation:
    #   max_megabytes: 10
    #   max_days: 3
    #   max_backups: 3
    #   localtime: true

  # HTTP exporter for sending data to Docent's /trace endpoint
  otlphttp/docent:
    endpoint: http://host.docker.internal:8889/rest/telemetry/
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file, otlphttp/docent]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file, otlphttp/docent]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file, otlphttp/docent]

  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
